services:
  api:
    image: hx-api:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.api
    ports:
      - "8000:8000"
  worker:
    image: hx-worker:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile.worker
  redis:
    image: "redis:latest"
