services:
  api:
    image: hx-api:latest
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      DEV: ${DEV}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGHOST: ${PGHOST}
      PGDATABASE: ${PGDATABASE}

    develop:
      watch:
        - path: ./hanzi_xiangqin
          action: sync
          target: /app/hanzi_xiangqin

  setup:
    image: hx-api:latest
    command: [ ".venv/bin/python", "-m", "hanzi_xiangqin", "setup" ]
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    environment:
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      ROOT_PGPASSWORD: ${ROOT_PGPASSWORD}
      PGHOST: ${PGHOST}
      PGDATABASE: ${PGDATABASE}

  worker:
    image: hx-worker:latest
    build:
      context: .
      dockerfile: ./docker/worker.Dockerfile
    develop:
      watch:
        - path: ./hanzi_xiangqin
          action: sync+restart
          target: /app/hanzi_xiangqin

  ui:
    image: hx-ui:latest
    build:
      context: ./ui
      dockerfile: ../docker/ui.Dockerfile
      target: development
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: ./ui
          action: sync
          target: /app
          ignore:
            - node_modules

  redis:
    image: "redis:latest"

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${ROOT_PGPASSWORD}
      POSTGRES_DB: postgres

