services:
  api:
    image: hx-api:latest
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEV=true
    develop:
      watch:
        - path: ./hanzi_xiangqin
          action: sync
          target: /app/hanzi_xiangqin
  worker:
    image: hx-worker:latest
    build:
      context: .
      dockerfile: ./docker/worker.Dockerfile
    develop:
      watch:
        - path: ./hanzi_xiangqin
          action: sync+restart
          target: /app/hanzi_xiangqin
  ui:
    image: hx-ui:latest
    build:
      context: .
      dockerfile: ./docker/ui.Dockerfile
      target: development
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: ./ui/app
          action: sync
          target: /app/app
        - path: ./ui/public
          action: sync
          target: /app/public
  redis:
    image: "redis:latest"
