name: CI pipeline

on: push

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Run checks
      run: |
          uv sync --all-groups
          uv run ruff check hanzi_xiangqin
          uv run mypy hanzi_xiangqin

  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: "redis:latest"
      db:
        image: "postgres:latest"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: replaceme
          POSTGRES_DB: postgres

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Run tests
      run: |
          uv sync --all-groups
          uv run coverage run --source hanzi_xiangqin -m pytest tests/ -svv
          uv run coverage report -m
